#!/bin/bash

if ! less /etc/os-release | grep -i "NAME=Fedora" > /dev/null; then
    step "incompatible distribution"
    exit 0
fi

PACKAGES=(
    pipewire-libpulse
    pipewire-libjack
    pipewire-alsa
    pipewire-gstreamer
)

step "installing packages"
pkg-install "${PACKAGES[@]}"
