#!/bin/sh
set -e

if ! hash ansible > /dev/null; then
  sudo dnf install -y ansible
fi

ansible-galaxy collection install community.general > /dev/null

ansible-playbook bootstrap.yml --ask-become-pass --extra-vars "@vars.yml"
