#!/bin/bash

function install_uhe_plugin {
    step "installing $1"

    local url_prefix='https://dl.u-he.com/releases'
    local file="$(download "${url_prefix}/$2" "$1.tar.xz" "$3")"
    local tar_tmp="$(mktemp -d)"
    (
        cd "$tar_tmp" && tar -xf "$file" --strip-components=1
        ./install.sh --quiet
    )

    rm -rf "$tar_tmp"
}

install_uhe_plugin \
    'uhe-hive' \
    'Hive_211_12092_Linux.tar.xz' \
    '063acb53bbf4e46be4c70c9b69265576'

install_uhe_plugin \
    'uhe-zebralette' \
    'Zebra2_293_12092_Linux.tar.xz' \
    '1c57d98fd5cf12550ca366620f50e01b'

install_uhe_plugin \
    'uhe-podolski' \
    'Podolski_123_12092_Linux.tar.xz' \
    'e84e6030a68ae0383b4fb6c1597c6c0e'

install_uhe_plugin \
    'uhe-tripple-cheese' \
    'TripleCheese_13_12092_Linux.tar.xz' \
    '0aa3e44cd8473107eabbed3bdd65359a'

# yabridge
if hash dnf 2>/dev/null; then
    step "Installing yabridge"
    sudo dnf copr enable "patrickl/yabridge" -y
    sudo dnf install yabridge -y
fi

yabridgectl add ~/.vst
yabridgectl add ~/.vst3
