#!/bin/bash

url='https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz'
md5='f0497d8fd2b9b6cc3bbeb07c9dca7e22'
file="$(download "$url" "texlive-unix.tar.gz" "$md5")"
(
    cd "$(mkdir -p)" || exit 1
    zcat < "$file" | tar xf -
    cd install-tl-* || exit 1
    sudo ./install-tl
)
