#!/bin/env bash
PACKAGES=(
  # shell
  ack
  ripgrep
  ShellCheck
  inotify-tools
  # dev
  gcc
  g++
  gdb
  patchelf
  meson
  ninja-build
  cmake
  # apps
  tilp2      # ti calculator communication
  neovim
  keepassxc
  flac
  maxima
  cantor # maxima ui
  piper  # mouse configuration
  #youtube-dl
  yt-dlp
  rofi
  picard
  hdparm
  p7zip
  p7zip-plugins
  maildir-utils
  isync
  borgbackup
  podman
  podman-docker
  krita
  # audio
  pavucontrol
  timidity++
  # fonts
  adobe-source-code-pro-fonts
  adobe-source-serif-pro-fonts
  adobe-source-sans-pro-fonts
  fontawesome-fonts
  powerline-fonts
  # latex
  lilypond
  texlive-latex
  texlive-latex-fonts
  texlive-context
  texlive-collection-langgerman
  texlive-ec
  texlive-cm-super
  texlive-wrapfig
  texlive-ulem
  texlive-capt-of
  texlive-parskip
  texlive-dvipng
  texlive-dvisvgm
  texlive-tcolorbox
)

step "installing packages"
pkg-install "${PACKAGES[@]}"
