#!/bin/env bash

if ! less /etc/os-release | grep -i "NAME=Fedora" > /dev/null; then
    step "incompatible distribution"
    exit 0
fi

PACKAGES=(
  # shell
  ack
  ripgrep
  ShellCheck
  inotify-tools
  # dev
  gcc
  g++
  gdb
  ccls
  patchelf
  meson
  ninja-build
  cmake
  # apps
  flameshot
  neovim
  keepassxc
  flac
  youtube-dl
  rofi
  picard
  hdparm
  p7zip
  p7zip-plugins
  maildir-utils
  isync
  borgbackup
  podman
  podman-docker
  krita
  # audio
  pavucontrol
  timidity++
  # fonts
  adobe-source-code-pro-fonts
  adobe-source-serif-pro-fonts
  adobe-source-sans-pro-fonts
  fontawesome-fonts
  powerline-fonts
  # latex
  lilypond
  texlive-latex
  texlive-latex-fonts
  texlive-context
  texlive-collection-langgerman
  texlive-ec
  texlive-cm-super
  texlive-wrapfig
  texlive-ulem
  texlive-capt-of
  texlive-parskip
  texlive-dvipng
  texlive-dvisvgm
)

step "installing packages"
pkg-install "${PACKAGES[@]}"
