#!/bin/env bash
set -eu

step "adding flathub"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

step "installing flatpak"
flatpak install flathub com.bitwig.BitwigStudio/x86_64/stable
