#!/bin/env bash
set -eu

#step "adding flathub"
#flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#step "installing flatpak"
#flatpak install flathub com.bitwig.BitwigStudio/x86_64/stable

pkg-install dpkg

if [[ -x "$HOME/.local/bin/bitwig-install" ]];
then
   "$HOME/.local/bin/bitwig-install" "4.4.6"
fi

step "Installing yabridge"
sudo dnf copr enable "patrickl/yabridge-stable" -y
sudo dnf install yabridge -y
#yabridgectl add "$HOME/.vst"
#yabridgectl add "$HOME/.vst3"
#yabridgectl sync
