#!/bin/bash

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

apps=(
    #com.spotify.Client
    #im.riot.Riot
    com.belmoussaoui.Authenticator
    com.discordapp.Discord
    com.github.tchx84.Flatseal
    com.makemkv.MakeMKV
    com.teamspeak.TeamSpeak
    #de.haeckerfelix.Shortwave
    io.github.celluloid_player.Celluloid # MPV frontend
    org.gimp.GIMP
    org.gnome.World.PikaBackup
    org.inkscape.Inkscape
    org.kde.kcachegrind # Valgrind visualizer
    org.kde.massif-visualizer # Valgrind massif visualizer
    org.remmina.Remmina # VNC/RDP client
    org.signal.Signal
    org.telegram.desktop
    #org.gnome.Calls # SIP Phone (not working)
    #com.icanblink.blink # SIP Phone (working)
)

flatpak install --or-update -y flathub "${apps[@]}"
