#!/bin/bash

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

apps=(
    org.gimp.GIMP
    org.inkscape.Inkscape
    de.haeckerfelix.Shortwave
    com.discordapp.Discord
    org.telegram.desktop
    org.signal.Signal
    #im.riot.Riot
    com.teamspeak.TeamSpeak
    com.makemkv.MakeMKV
    org.videolan.VLC
    org.kde.massif-visualizer # Valgrind massif visualizer
    org.kde.kcachegrind # Valgrind visualizer
    #org.remmina.Remmina # VNC/RDP client
    #com.spotify.Client
    #com.github.tchx84.Flatseal
)

flatpak install -y flathub "${apps[@]}"
