#!/bin/bash

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

apps=(
    org.gimp.GIMP
    de.haeckerfelix.Shortwave
    com.discordapp.Discord
    com.makemkv.MakeMKV
    com.teamspeak.TeamSpeak
    org.videolan.VLC
    org.kde.massif-visualizer
    org.kde.kcachegrind
    #com.spotify.Client
    #com.github.tchx84.Flatseal
    #im.riot.Riot
)

flatpak install -y flathub "${apps[@]}"
