#!/bin/bash
set -eu

VERSION="0.10.0"
URL="https://github.com/typst/typst/releases/download/v${VERSION}/typst-x86_64-unknown-linux-musl.tar.xz"

#if ! hash typst-${VERSION} 2>/dev/null; then
#    step "Downloading typst ${VERSION}"
#
#    file="$(download "$URL" "typst-${VERSION}")"
#
#    cp "$file" "$HOME/.local/bin/"
#    (cd "$HOME/.local/bin" || exit 1
#     [[ -f typst ]] && rm typst
#     tar -xf "typst-${VERSION}"
#     chmod a+x "typst-${VERSION}"
#     "typst-${VERSION}" -v
#     mv typst-x86_64-unknown-linux-musl/typst ./
#     rm -rf typst-x86_64-unknown-linux-musl
#    )
#fi

#VERSION="0.10.1"
#URL="https://github.com/nvarner/typst-lsp/releases/download/v${VERSION}/typst-lsp-x86_64-unknown-linux-gnu"
#
#if ! hash typst-lsp-${VERSION} 2>/dev/null; then
#    step "Downloading typst-lsp ${VERSION}"
#
#    file="$(download "$URL" "typst-lsp-${VERSION}")"
#    cp "$file" "$HOME/.local/bin/typst-lsp"
#    chmod a+x "$HOME/.local/bin/typst-lsp"
#fi
