#!/bin/bash

if ! hash zsh 2>/dev/null; then
    pkg-install zsh #starship
fi

if ! grep "$USER.*/zsh" /etc/passwd > /dev/null; then
    step "setting user shell to zsh"
    sudo usermod -s /usr/bin/zsh "${SUDO_USER:-${USER}}"
fi
