#!/bin/env bash

if [[ ! -d "${HOME}/.emacs.d" ]]; then
    step 'cloning doom to ~/.emacs.d'
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d >/dev/null

    step 'installing doom emacs'
    ~/.emacs.d/bin/doom install >/dev/null
fi
