#!/bin/env bash

pkg-install --bin git

step "setting email address"
local_config_file="${XDG_CONFIG_HOME:-~/.config/}/git/config.local"
if [[ ! -f "$local_config_file" ]]; then
    read -rp "email? " gitmail < /dev/tty

    mkdir -p "${XDG_CONFIG_HOME:-~/.config/}/git"
    cat <<EOF > "$local_config_file"
[user]
    email = "$gitmail"
EOF
fi
