#!/bin/bash

step "Writing udev rule"
sudo tee /etc/udev/rules.d/69-n-link.rules <<EOF
# TI-Nspire
SUBSYSTEM=="usb", ATTR{idVendor}=="0451", ATTR{idProduct}=="e012", ENV{ID_PDA}="1"
# TI-Nspire CX II
SUBSYSTEM=="usb", ATTR{idVendor}=="0451", ATTR{idProduct}=="e022", ENV{ID_PDA}="1"
EOF

step "Triggering udev"
sudo udevadm control --reload-rules && sudo udevadm trigger

step "Downloading AppImage"
cd "$HOME/Downloads" || exit
wget 'https://github.com/lights0123/n-link/releases/download/v0.1.6/desktop_0.1.6_amd64.AppImage' \
    -O 'N-Link' && chmod a+x 'N-Link' && cp 'N-Link' "$HOME/.local/bin/"

step "Installing packages"
pkg-install tilp2
