---
- name: Installing neovim
  dnf:
    name:
      - neovim
    state: present
  become: true

- name: Linking neovim config
  file:
    src: "{{ role_path }}/files"
    dest: "{{ nvim_home }}"
    state: link
